### ISSUE TITLE
Traceback Error

### ISSUE THREAD

**Issue by mbrgpt** [devgc/EventMonkey#16]
Trying this out for the first time and kept getting the following error:

Traceback (most recent call last):
  File "H:\Downloads\EventMonkey-master\EventMonkey.py", line 43, in <module>
    import libem.WindowsEventManager as WindowsEventManager
  File "H:\Downloads\EventMonkey-master\libem\WindowsEventManager.py", line 121
    print u'File needs .evt or .evtx extention. {}'.format(DEBUG_FILE)

**Comment by devgc** [comment]
Are you using the compiled version?

**Comment by devgc** [comment]
Can you give the command you used?

**Comment by mbrgpt** [comment]
EventMonkey.py process -n NAME -p PATHTOLOGS -o OUTPUT

**Comment by devgc** [comment]
I cannot seem reproduce. That error is coming from a function that gets called if you are running WindowsEventManger.py as the main script. I'm not sure why it is executing when you are running EventMonkey.py as the main script. I went ahead and removed it though. Try installing (```setup.py install```) from the main branch now and see if it is fixed. I have only ever ran with python 27 in Windows, not sure if that makes a difference or not either.

**Comment by mbrgpt** [comment]
I will try the suggestions. I am running 3.5.1; I will also try 2.7.
