### ISSUE TITLE
ImportError: No module named gchelpers.db.DbHandler

### ISSUE THREAD

**Issue by jpoling-dswrx** [devgc/EventMonkey#17]
`# python EventMonkey.py -f xlsx_templates/ -p Events/ -o Events/`
> Traceback (most recent call last):
  File "EventMonkey.py", line 46, in <module>
    from gchelpers.db.DbHandler import DbConfig
ImportError: No module named gchelpers.db.DbHandler

Are the [gchelpers modules](https://github.com/devgc/GcHelpers) now a requirement for this?

**Comment by devgc** [comment]
There are now two sub commands. process, and report. See `EventMonkey.py -h` and `EventMonkey.py process -h`. The report subcommand is so you can re-run templates without parsing again. See 'EventMonkey.py report -h'.

You would want to use `EventMonkey.py process -n NAME -p Events/ -o Events/` use -f if you have custom templates, other wise it will automatically use the templates that come with it.

```
EventMonkey (A Windows Event Parsing Utility)

positional arguments:
  {process,report}      Either process or report command is required.
    process             Processes eventfiles and then generate reports.
    report              Generate reports from an existing EventMonkey
                        database.
```

**Comment by devgc** [comment]
Ah, but yes, the gchelpers module is now a requirement. It should be in the setup script, so a `setup.py install` should grab it for you.

**Comment by devgc** [comment]
I updated the dependencies in the [readme](https://github.com/devgc/EventMonkey/blob/master/README.md#dependencies)

**Comment by jpoling-dswrx** [comment]
Great. Thanks!
